### ISSUE TITLE
New noms serialization

### ISSUE THREAD

**Issue by ghost** [attic-labs/noms#1105]
This is meta bug of other bugs which require changes to the noms serialization

In my mind, this is core work and I hope uncontreversial:
- [x] #1121 Disallow Untyped Refs in the API & Serialization
- [x] #814 Make .noms structs field order non-significant
- [x] #1164 A type's identity shouldn't depend on other types in the same package
- [x] #1165 Remove type references (i.e. writing type definitions in a separate chunk)
- [x] #1104 Kind.Ref should not be "ordered"
- [x] #422 NomDL Serialization: Use binary
- [ ] #1086 Noms serialization forces excessive passes
- [x] #617 Chunk over value byte serialization rather than ref
- [ ] #1562 Need a way to skip over values in the serialization

This is work which may be implied by other features, improvements of related changes:
- [x] #764 Implement efficient Len for chunked sets and maps
- [x] #279 Move to sha-2
- [x] #1106 Refs in MetaTuples should be typed correctly
- [x] #1138 Get rid of sized ints & floats
- [x] #1087 Consider a type system which is more "structural"
