### ISSUE TITLE
command line porcelain cleanup

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#1147]
We want to cleanup the [porcelain](http://stackoverflow.com/questions/6976473/what-does-the-term-porcelain-mean-in-git) to be a lot more consistent and professional.

See design doc:

https://docs.google.com/document/d/1QgKcRS304llwU0ECahKtn8lGBFmT5zXzWr-5tah1S_4/edit

Here are the main sub-tasks:
- [ ] Implement `noms-show`
- [ ] Implement `noms-set`
- [ ] Implement `noms-log`
- [ ] Implement `noms-sync` - #1150 
- [ ] Implement `noms-clone` - #1151 
- [ ] Implement `noms-diff`
- [ ] Implement `noms` wrapper command - #1152 
- [ ] We need a human-readable noms serialization - #1153 

Note that the design doc specifies a syntax for datastore, dataset, and object arguments that is different from the mechanism we currently use. There probably needs to be some helper functions created that will be used by all Go code to handle this new syntax.

@cmasone-attic, @rafael-atticlabs
