### ISSUE TITLE
oss launch!

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#1222]
Commands (using new porcelain)
- [x] sync - 0 - #1150
- [x] show - 0 - #1148
- [ ] diff - 0 - #1272
- [x] log - 0 - #1273 
- [x] set - 0 - #1149
- [x] noms - 0 - #1152

Examples
- [x] counter
- [x] csv import/export
- [x] json import
  - [ ] ideally, import as strongly typed data! - 2
- [x] xml import
- [x] fs import - 2
- [x] splore
- [ ] add `examples` directory that has executable scripts that both demonstrate how to piece things together into pipelines and test all the examples
  - two of the examples will be the demos below, and others can be made from whatever we have checked in at the time.

Core
- [x] Rename Datastore -> Database - 1 #1290
- [x] Restrict dataset and field names - 1 #1402 
- [x] New Type System -  0 #1266 
- [x] Finish Patent - 0
- [x] Fix ldb scoping thing - 0 #1263
- [x] human readable serialization - 0 #1153
- [x] fast push/pull - 2 #1564
- [ ] commit validation - 0 #1481

Docs
- [x] JS library tour - 0
- [ ] Go library tour - 0
- [x] Cmdline tour - 0
- [ ] Noms intro / design overview - 0
- [ ] Prolly trees - 0
- [x] Spelling objects/datastores/datasets -- commands will refer to this - 0

Important bugs that should have design sketches
- [ ] Serialization v.Next - 1 #1105
- [ ] GC - 0 #25 
- [ ] A plan for versioning - 1 #1561
- [ ] bignum - 1 #1138

Marketing/Launch support
- [ ] Splash page - 0 - #1411
- [ ] Medium post (history and inspiration for noms) - 0
- [x] Greylock announcement - [Draft](https://docs.google.com/document/d/1sTnTIYR3UOgOf5_a7LGHMtIDJe3R-A9AnquhA16I5ao/edit) - 0
- [ ] Screencast - [Script](https://docs.google.com/document/d/1OYLqO58PEICcJvsX7RDSGFbIVmlKroW_jVXcQ81O01g/edit#) - 0
  - [ ] Sync demo
    - [ ] Bring back dev.noms.io in some form - #1445
    - [ ] Pick and test a good dataset to sync - #1444 
  - [ ] Attic
    - [x] Flickr
    - [ ] Picasa
    - [ ] Facebook
    - [ ] Visionator
    - [ ] Index by date / tag
    - [ ] UI to display result of index
  - [ ] SF Construction
    - [ ] SF Construction Prep Indexer
    - [ ] Heatmap
- [ ] Email to friends/family/supporters - 0
