### ISSUE TITLE
Implement dynamic typing

### ISSUE THREAD

**Issue by ghost** [attic-labs/noms#1266]
@aboodman Has a longer write up of this idea here: https://docs.google.com/a/atticlabs.io/document/d/1O-nOAJ5s9X484Ubj3089lZ0_fBsNJfZVxTQnSKQ7oHA/edit?usp=drivesdk

This is a meta bug which will track the work to get from where we are now to where we want to be.
- [x] #1267 Implement Ref.height
- [x] #1121 Disallow Untyped Refs in the API & Serialization
- [x] #1265 Remove go codegen & examples which use it
- [x] #1261 Remove go codegen from datas & types
- [x] #814 Make .noms structs field order non-significant
- [x] #1164 Remove packages
- [x] #1165 Remove type references (i.e. writing type definitions in a separate chunk)
- [x] #1104 Kind.Ref should not be "ordered"
- [x] #764 Implement efficient Len for chunked sets and maps
- [x] #1308 Noms serialization must include type for every value
- [x] #1309 Remove all number types but float64
- [x] #1310 remove enums & optional fields
- [x] #1344 remove unions from structs
- [x] #1311 implement union (sum) type
- [x] #1312 collections must support heterogeneous element types
- [x] #1491 Update collection APIs to refine types
