### ISSUE TITLE
Commit Validation code simplification 

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1580]
- [ ] Tighten up Hints semantics #1569
- [ ] ref cache grows without bound #1570 
- [ ] make Refs self-validating #1573
- [ ] can hints also live on Refs? #1576
- [ ] We want to use the best hints #1575
- [ ] Make sure validation won't fail when re-trying on ErrOptimisticLockFailed #1579
- [ ] Http batch store leaves a window between writeValue and updateRoot #1578

FYI @rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
buh bye: https://github.com/attic-labs/noms/commit/de76d37f098d4873665fe27a73d5fa5fb7162d66
