### ISSUE TITLE
Miscellaneous diff format cleanups

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2138]
Some sample output from current code with (parenthesized issue markers) in margin. See below for details of each issue.

```
./.meta {
-   "date": "2016-07-23T01:46:50+0000" (6)
+   "date": "2016-07-23T07:33:27+0000"
-   "inputPath": "http://localhost:8000/cli-tour?access_token=yeknom::sf-crime/raw.value" (1)
+   "inputPath": "http://demo.noms.io/cli-tour?access_token=yeknom::sf-crime/raw.value" (2)
./.parents {
-   0jn8dh71tbjj1eis33a1rpgjjltr982t
+   qkka7siu8h6pfbhg5j1hljhpkfkv2a0q
  } (3)
./.value."13055137904092" {
-   "Address": "HARRISON ST / 23RD ST"
+   "Address": "23RD ST / HARRISON ST"
-   "Date": "07/04/2013"
+   "Date": "07/04/2016"
-   "DayOfWeek": "Thursday"
+   "DayOfWeek": "Monday" (4)
+   "13055137973000":  { (5)
+     Address: "23RD ST / HARRISON ST",
...
+     Y: "37.7542302702624",
+   }
```

Note that these all have different priorities. See individual bugs for their priorities.

- [x] - (1) Don't pass access token to read requests - #2135
- [x] - (2) Also record input hash - #2113
- [x] - (3) Include closing brace in diff output for struct/map - #2136
- [x] - (4) Add newline between chunks of changes - #2137
- [x] - (5) Indenting of changed records inconsistent wrt added/removed records - #2133
- [x] - (6) Don't quote field names when structs are modified - #2139

With these changes, output should be like:

```
  ./.meta {
-   date: "2016-07-23T01:46:50+0000" (6)
+   date: "2016-07-23T07:33:27+0000"
-   inputPath: "http://localhost:8000/cli-tour::sf-crime/raw.value" (1)
+   inputPath: "http://demo.noms.io/cli-tour?::sf-crime/raw.value"
-   inputHash: "0jn8dh71tbjj1eis33a1rpgjjltr982t" (2)
+   inputHash: "qkka7siu8h6pfbhg5j1hljhpkfkv2a0q"
  }

  ./.parents {
-   0jn8dh71tbjj1eis33a1rpgjjltr982t
+   qkka7siu8h6pfbhg5j1hljhpkfkv2a0q
  } (3)

  ./.value."13055137904092" {
-   Address: "HARRISON ST / 23RD ST"
+   Address: "23RD ST / HARRISON ST"
-   Date: "07/04/2013"
+   Date: "07/04/2016"
-   DayOfWeek: "Thursday"
+   DayOfWeek: "Monday"
  } (4)

+ ./.value."13055137973000":  { (5)
+   Address: "23RD ST / HARRISON ST",
...
+   Y: "37.7542302702624",
+ }
```

**Comment by kalman** [comment]
Everything done, closing.

**Comment by aboodman** [comment]
+1
