### ISSUE TITLE
NomDL: Support imports

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#294]
We know we want Noms type packages to be able to reference types defined in other types packages. When @aboodman and I initially talked about this, we decided we definitely wanted devs to be able to import packages by ref, but we may also want to allow them to do so by path. I think that, if you're a developer that's creating several type packages, making a change to one and then having to generate its ref and update all places you import it would become tedious. That said, I think that importing by path should be some kind of syntactic sugar for importing by ref; the tools would handle finding the import and generating its ref, and then use that when resolving symbols and such.

Because we want to refer to type packages by ref, I think this means we need to do the work of converting a package into Noms data structures before we can really dig into imports. @aboodman and @arv -- thoughts?

There's also the related question of having multiple .noms files that are part of a single type package. We thought maybe we'd do this like Go does, where all the files in a given directory are automatically put in the same package, and definitions from one are visible to all.

Ok, definitely need to:
- [x] merge types.TypeRef and parse.TypeRef issue #338 
- [x] merge types.Package and parse.Package issue #353 
- [x] teach codegen to read/write packages from a datastore issue #366
- [x] generate code for imported packages issue #367
- [x] import packages by path #399
