### ISSUE TITLE
NomDL: Codegen

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#304]
- [x] New serialization format #421, #422
- [x] Codegen for List/Map/Set extras #303 
- [x] Codegen for Ref #306 
- [x] Renames fields/type to uppercase? #311
- [x] CodeGen for Struct should use Map for now #312
- [x] Get rid of $name
